/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/BillboardScript")]
    [LuaRegisterType(0x4a1809a4d4d6f8bf, typeof(LuaBehaviour))]
    public class BillboardScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b7352623c1ad89a468ff125eb1ec8f13";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_locUp = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_locUp),
            };
        }
    }
}

#endif
