/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CameraManager")]
    [LuaRegisterType(0x932352b34a99f09d, typeof(LuaBehaviour))]
    public class CameraManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "d47c339e9789352459c7a3cce8944871";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_FreeCam = default;
        [SerializeField] public UnityEngine.LayerMask m_FullVisibility = default;
        [SerializeField] public UnityEngine.LayerMask m_LocalVisibility = default;
        [SerializeField] public UnityEngine.LayerMask m_FullVisibilityTouch = default;
        [SerializeField] public UnityEngine.LayerMask m_LocalVisibilityTouch = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_FreeCam),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_FullVisibility),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_LocalVisibility),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_FullVisibilityTouch),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_LocalVisibilityTouch),
            };
        }
    }
}

#endif
