/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CameraRenderRate")]
    [LuaRegisterType(0xc6fa34863751e630, typeof(LuaBehaviour))]
    public class CameraRenderRate : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "47095103e72fb634197b99688853e8b2";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_framesBetweenRenders = 2;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_framesBetweenRenders),
            };
        }
    }
}

#endif
