/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CashItemScript")]
    [LuaRegisterType(0x3529d477d4c61906, typeof(LuaBehaviour))]
    public class CashItemScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "5fe5abbd110001f4dad9654bf8a3df53";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.ParticleSystem m_particle = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_particle),
            };
        }
    }
}

#endif
