/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ClothingPickupWorld")]
    [LuaRegisterType(0x7f99c9a05ff9196b, typeof(LuaBehaviour))]
    public class ClothingPickupWorld : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "fefe2695d124b2f41b378ec1f5163941";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.AnimationCurve m_easingCurve = default;
        [SerializeField] public System.String m_type = "";
        [SerializeField] public System.String m_ItemID = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_easingCurve),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_type),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_ItemID),
            };
        }
    }
}

#endif
