/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ClothingRack")]
    [LuaRegisterType(0x7d3194fe53416b8a, typeof(LuaBehaviour))]
    public class ClothingRack : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e8af60e029176904d965c745a9616d91";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_title = "";
        [SerializeField] public System.String m_clothingCollection = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_title),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_clothingCollection),
            };
        }
    }
}

#endif
