/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GameManager")]
    [LuaRegisterType(0x64f367123469100e, typeof(LuaBehaviour))]
    public class GameManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "471945008356f7b4d98b0452641d436c";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_mainCam = default;
        [SerializeField] public UnityEngine.GameObject m_TVCam = default;
        [SerializeField] public UnityEngine.Transform m_DressingRoom = default;
        [SerializeField] public UnityEngine.Transform m_RunwayA = default;
        [SerializeField] public UnityEngine.Transform m_RunwayB = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Transform> m_crowdPoints = default;
        [SerializeField] public UnityEngine.GameObject m_podiumMesh = default;
        [SerializeField] public UnityEngine.Transform m_GoldPoint = default;
        [SerializeField] public UnityEngine.Transform m_SilverPoint = default;
        [SerializeField] public UnityEngine.Transform m_BronzePoint = default;
        [SerializeField] public UnityEngine.ParticleSystem m_FireWorks = default;
        [SerializeField] public UnityEngine.ParticleSystem m_Confetti = default;
        [SerializeField] public UnityEngine.ParticleSystem m_Paparatzzi1 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_Paparatzzi2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_Paparatzzi3 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_Paparatzzi4 = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.ParticleSystem> m_rewardParticles = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_mainCam),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_TVCam),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_DressingRoom),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_RunwayA),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_RunwayB),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_crowdPoints),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_podiumMesh),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_GoldPoint),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_SilverPoint),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_BronzePoint),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_FireWorks),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_Confetti),
                CreateSerializedProperty(_script.GetPropertyAt(12), m_Paparatzzi1),
                CreateSerializedProperty(_script.GetPropertyAt(13), m_Paparatzzi2),
                CreateSerializedProperty(_script.GetPropertyAt(14), m_Paparatzzi3),
                CreateSerializedProperty(_script.GetPropertyAt(15), m_Paparatzzi4),
                CreateSerializedProperty(_script.GetPropertyAt(16), m_rewardParticles),
            };
        }
    }
}

#endif
