/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GetItemDevButton")]
    [LuaRegisterType(0x947f5c4400e0e707, typeof(LuaBehaviour))]
    public class GetItemDevButton : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "10cd2a04918dee440bd51279b3c1fa04";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_GiveItem = true;
        [SerializeField] public System.String m_Item = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_GiveItem),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Item),
            };
        }
    }
}

#endif
