/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/InventoryMetaData")]
    [LuaRegisterType(0xffcce8e019917342, typeof(LuaBehaviour))]
    public class InventoryMetaData : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "dff69d9c8f38a064484a3b77b43edddb";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Texture m_Heart_Aura_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Butterfly_Aura_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Hearts_Black_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Hearts_Pastel_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Hearts_Pink_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Hearts_Purple_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Hearts_Red_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Hearts_White_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Sparkles_Blue_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Sparkles_Green_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Sparkles_Pink_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Sparkles_Purple_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Sparkles_White_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Sparkles_Yellow_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Bats_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Bows_Pastel_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Cash_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Confetti_Player_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Feathers_Black_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Feathers_Colorfull_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Snowflakes_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Stars_Gold_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Stars_Pastel_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Tomato_React_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Black_Heart_React_Icon = default;
        [SerializeField] public UnityEngine.Texture m_White_Heart_React_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Sparkle_React_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Star_React_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Dollar_React_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Gold_React_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Imp_React_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Eyes_React_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Heart_Eyes_React_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Small_Package_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Medium_Package_Icon = default;
        [SerializeField] public UnityEngine.Texture m_Large_Package_Icon = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Heart_Aura_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Butterfly_Aura_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_Hearts_Black_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_Hearts_Pastel_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_Hearts_Pink_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_Hearts_Purple_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_Hearts_Red_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_Hearts_White_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_Sparkles_Blue_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_Sparkles_Green_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_Sparkles_Pink_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_Sparkles_Purple_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(12), m_Sparkles_White_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(13), m_Sparkles_Yellow_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(14), m_Bats_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(15), m_Bows_Pastel_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(16), m_Cash_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(17), m_Confetti_Player_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(18), m_Feathers_Black_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(19), m_Feathers_Colorfull_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(20), m_Snowflakes_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(21), m_Stars_Gold_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(22), m_Stars_Pastel_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(23), m_Tomato_React_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(24), m_Black_Heart_React_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(25), m_White_Heart_React_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(26), m_Sparkle_React_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(27), m_Star_React_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(28), m_Dollar_React_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(29), m_Gold_React_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(30), m_Imp_React_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(31), m_Eyes_React_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(32), m_Heart_Eyes_React_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(33), m_Small_Package_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(34), m_Medium_Package_Icon),
                CreateSerializedProperty(_script.GetPropertyAt(35), m_Large_Package_Icon),
            };
        }
    }
}

#endif
