/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ParticleButton")]
    [LuaRegisterType(0x9746bf11c16b9c8f, typeof(LuaBehaviour))]
    public class ParticleButton : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1c593f766718c4d478718de4bcccdced";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_partID = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_partID),
            };
        }
    }
}

#endif
