/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PlayerParticleController")]
    [LuaRegisterType(0xcd554c4b1b0ea7e2, typeof(LuaBehaviour))]
    public class PlayerParticleController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f1783897d7a7293469e2d9658cc21c81";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Transform m_particleParent = default;
        [SerializeField] public UnityEngine.ParticleSystem m_heartsAura = default;
        [SerializeField] public UnityEngine.ParticleSystem m_butterflies = default;
        [SerializeField] public UnityEngine.ParticleSystem m_heartsBlack = default;
        [SerializeField] public UnityEngine.ParticleSystem m_heartsPastel = default;
        [SerializeField] public UnityEngine.ParticleSystem m_heartsPink = default;
        [SerializeField] public UnityEngine.ParticleSystem m_heartsPurple = default;
        [SerializeField] public UnityEngine.ParticleSystem m_heartsRed = default;
        [SerializeField] public UnityEngine.ParticleSystem m_heartsWhite = default;
        [SerializeField] public UnityEngine.ParticleSystem m_sparklesBlue = default;
        [SerializeField] public UnityEngine.ParticleSystem m_sparklesGreen = default;
        [SerializeField] public UnityEngine.ParticleSystem m_sparklesPink = default;
        [SerializeField] public UnityEngine.ParticleSystem m_sparklesPurple = default;
        [SerializeField] public UnityEngine.ParticleSystem m_sparklesWhite = default;
        [SerializeField] public UnityEngine.ParticleSystem m_sparklesYellow = default;
        [SerializeField] public UnityEngine.ParticleSystem m_bats = default;
        [SerializeField] public UnityEngine.ParticleSystem m_bowsPastel = default;
        [SerializeField] public UnityEngine.ParticleSystem m_cash = default;
        [SerializeField] public UnityEngine.ParticleSystem m_confettiPlayer = default;
        [SerializeField] public UnityEngine.ParticleSystem m_feathersBlack = default;
        [SerializeField] public UnityEngine.ParticleSystem m_feathersColorfull = default;
        [SerializeField] public UnityEngine.ParticleSystem m_snowflakes = default;
        [SerializeField] public UnityEngine.ParticleSystem m_starsGold = default;
        [SerializeField] public UnityEngine.ParticleSystem m_starsPastel = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_particleParent),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_heartsAura),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_butterflies),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_heartsBlack),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_heartsPastel),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_heartsPink),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_heartsPurple),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_heartsRed),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_heartsWhite),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_sparklesBlue),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_sparklesGreen),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_sparklesPink),
                CreateSerializedProperty(_script.GetPropertyAt(12), m_sparklesPurple),
                CreateSerializedProperty(_script.GetPropertyAt(13), m_sparklesWhite),
                CreateSerializedProperty(_script.GetPropertyAt(14), m_sparklesYellow),
                CreateSerializedProperty(_script.GetPropertyAt(15), m_bats),
                CreateSerializedProperty(_script.GetPropertyAt(16), m_bowsPastel),
                CreateSerializedProperty(_script.GetPropertyAt(17), m_cash),
                CreateSerializedProperty(_script.GetPropertyAt(18), m_confettiPlayer),
                CreateSerializedProperty(_script.GetPropertyAt(19), m_feathersBlack),
                CreateSerializedProperty(_script.GetPropertyAt(20), m_feathersColorfull),
                CreateSerializedProperty(_script.GetPropertyAt(21), m_snowflakes),
                CreateSerializedProperty(_script.GetPropertyAt(22), m_starsGold),
                CreateSerializedProperty(_script.GetPropertyAt(23), m_starsPastel),
            };
        }
    }
}

#endif
