/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TapHandlerControllerJoystick")]
    [LuaRegisterType(0x9fd0fe65165112c4, typeof(LuaBehaviour))]
    public class TapHandlerControllerJoystick : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "5b1b9c18fd287cb4d85fea4f8ec058c5";
        public override string ScriptGUID => s_scriptGUID;


        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
            };
        }
    }
}

#endif
