/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManager")]
    [LuaRegisterType(0x4420fd164eed93fa, typeof(LuaBehaviour))]
    public class UIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "6fcbf184e6d6a2f468dea7a30d83f458";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_ButtonsObject = default;
        [SerializeField] public UnityEngine.GameObject m_InventoryObject = default;
        [SerializeField] public UnityEngine.GameObject m_LeaderboardObject = default;
        [SerializeField] public UnityEngine.GameObject m_OverlayObject = default;
        [SerializeField] public UnityEngine.GameObject m_VotingObject = default;
        [SerializeField] public UnityEngine.GameObject m_ShopObject = default;
        [SerializeField] public UnityEngine.GameObject m_WorldHudObject = default;
        [SerializeField] public UnityEngine.GameObject m_InteractionObject = default;
        [SerializeField] public UnityEngine.GameObject m_EmotesObject = default;
        [SerializeField] public UnityEngine.GameObject m_RankingObject = default;
        [SerializeField] public UnityEngine.GameObject m_selectedClothingObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_ButtonsObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_InventoryObject),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_LeaderboardObject),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_OverlayObject),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_VotingObject),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_ShopObject),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_WorldHudObject),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_InteractionObject),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_EmotesObject),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_RankingObject),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_selectedClothingObject),
            };
        }
    }
}

#endif
