/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/VotingGUI")]
    [LuaRegisterType(0x5945fee95f5cdf49, typeof(LuaBehaviour))]
    public class VotingGUI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f82e10d4cb33afa49a30126c1707cbb7";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.AnimationCurve m_bounceCurve = default;
        [SerializeField] public UnityEngine.Texture m_emptyIcon = default;
        [SerializeField] public UnityEngine.Texture m_RatingOne = default;
        [SerializeField] public UnityEngine.Texture m_RatingTwo = default;
        [SerializeField] public UnityEngine.Texture m_RatingThree = default;
        [SerializeField] public UnityEngine.Texture m_RatingFour = default;
        [SerializeField] public UnityEngine.Texture m_RatingFive = default;
        [SerializeField] public UnityEngine.ParticleSystem m_heartParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_fireParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_clapParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_tomatoParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_BlackHeartParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_WhiteHeartParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_SparkleParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_StarParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_DollarParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_GoldParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_ImpParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_EyeParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_HeartEyeParts = default;
        [SerializeField] public UnityEngine.ParticleSystem m_heartParts2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_fireParts2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_clapParts2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_tomatoParts2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_BlackHeartParts2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_WhiteHeartParts2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_SparkleParts2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_StarParts2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_DollarParts2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_GoldParts2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_ImpParts2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_EyeParts2 = default;
        [SerializeField] public UnityEngine.ParticleSystem m_HeartEyeParts2 = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_bounceCurve),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_emptyIcon),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_RatingOne),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_RatingTwo),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_RatingThree),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_RatingFour),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_RatingFive),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_heartParts),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_fireParts),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_clapParts),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_tomatoParts),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_BlackHeartParts),
                CreateSerializedProperty(_script.GetPropertyAt(12), m_WhiteHeartParts),
                CreateSerializedProperty(_script.GetPropertyAt(13), m_SparkleParts),
                CreateSerializedProperty(_script.GetPropertyAt(14), m_StarParts),
                CreateSerializedProperty(_script.GetPropertyAt(15), m_DollarParts),
                CreateSerializedProperty(_script.GetPropertyAt(16), m_GoldParts),
                CreateSerializedProperty(_script.GetPropertyAt(17), m_ImpParts),
                CreateSerializedProperty(_script.GetPropertyAt(18), m_EyeParts),
                CreateSerializedProperty(_script.GetPropertyAt(19), m_HeartEyeParts),
                CreateSerializedProperty(_script.GetPropertyAt(20), m_heartParts2),
                CreateSerializedProperty(_script.GetPropertyAt(21), m_fireParts2),
                CreateSerializedProperty(_script.GetPropertyAt(22), m_clapParts2),
                CreateSerializedProperty(_script.GetPropertyAt(23), m_tomatoParts2),
                CreateSerializedProperty(_script.GetPropertyAt(24), m_BlackHeartParts2),
                CreateSerializedProperty(_script.GetPropertyAt(25), m_WhiteHeartParts2),
                CreateSerializedProperty(_script.GetPropertyAt(26), m_SparkleParts2),
                CreateSerializedProperty(_script.GetPropertyAt(27), m_StarParts2),
                CreateSerializedProperty(_script.GetPropertyAt(28), m_DollarParts2),
                CreateSerializedProperty(_script.GetPropertyAt(29), m_GoldParts2),
                CreateSerializedProperty(_script.GetPropertyAt(30), m_ImpParts2),
                CreateSerializedProperty(_script.GetPropertyAt(31), m_EyeParts2),
                CreateSerializedProperty(_script.GetPropertyAt(32), m_HeartEyeParts2),
                CreateSerializedProperty(_script.GetPropertyAt(33), null),
                CreateSerializedProperty(_script.GetPropertyAt(34), null),
                CreateSerializedProperty(_script.GetPropertyAt(35), null),
                CreateSerializedProperty(_script.GetPropertyAt(36), null),
                CreateSerializedProperty(_script.GetPropertyAt(37), null),
                CreateSerializedProperty(_script.GetPropertyAt(38), null),
                CreateSerializedProperty(_script.GetPropertyAt(39), null),
                CreateSerializedProperty(_script.GetPropertyAt(40), null),
                CreateSerializedProperty(_script.GetPropertyAt(41), null),
                CreateSerializedProperty(_script.GetPropertyAt(42), null),
                CreateSerializedProperty(_script.GetPropertyAt(43), null),
                CreateSerializedProperty(_script.GetPropertyAt(44), null),
                CreateSerializedProperty(_script.GetPropertyAt(45), null),
                CreateSerializedProperty(_script.GetPropertyAt(46), null),
                CreateSerializedProperty(_script.GetPropertyAt(47), null),
                CreateSerializedProperty(_script.GetPropertyAt(48), null),
            };
        }
    }
}

#endif
